### ISSUE TITLE
Add Reset-Button

### ISSUE THREAD

**Issue by JakeSamu-Games** [simplefeedback/simplefeedback#24]
Add a button that is able to reset my vote on a given feedback. Could be nice to have if I've misclicked something ...

**Comment by Chessmasterrr** [comment]
The feature already exists, just click on the number (between up and down). But since you are the second test user to stumble upon it: maybe you have a suggestion on how to make it clearer?

maybe related to #18

**Comment by JakeSamu-Games** [comment]
Suggestion: everything that is clickable a small black/gray/whatever border. Or make the text/number a really light blue, similar to a url-link.

**Comment by Chessmasterrr** [comment]
Added some help texts, maybe that helps. Coming with the next release.
